title: IZICHANGEPAY

description: Nous sommes ravis de vous accueillir sur notre plateforme de portefeuille cryptomonnaie, conçue pour offrir une expérience sécurisée et efficace de gestion des actifs numériques. Que vous soyez un utilisateur débutant cherchant à explorer le monde des cryptomonnaies ou un investisseur chevronné, notre plateforme a été développée pour répondre à vos besoins.

theme: just-the-docs

url: https://github.com/cryptogateway-project/cryptogateway-project

logo: "/cryptogateway-project/assets/images/izi_logo.svg"

favicon_ico: "/cryptogateway-project/assets/images/favicon.ico"

callouts:
  highlight:
    color: highlight

aux_links:
  Dashboard: https://pay.izichange.com/
  Postman: https://interstellar-meadow-200044.postman.co/workspace/IZICHANGEPAY~fd629ce1-c63d-474f-8849-ddf8d1e51a9b/collection/30970679-072a1496-5b33-47b2-a1f8-ffe1ced74589/overview?action=share&creator=31682711



